/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as PaslauguTaisyklesRouteImport } from './routes/paslaugu-taisykles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const PaslauguTaisyklesRoute = PaslauguTaisyklesRouteImport.update({
  id: '/paslaugu-taisykles',
  path: '/paslaugu-taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRoute
  '/login': typeof LoginRoute
  '/paslaugu-taisykles': typeof PaslauguTaisyklesRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRoute
  '/login': typeof LoginRoute
  '/paslaugu-taisykles': typeof PaslauguTaisyklesRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRoute
  '/login': typeof LoginRoute
  '/paslaugu-taisykles': typeof PaslauguTaisyklesRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/paslaugu-taisykles'
    | '/privatumo-politika'
    | '/reset-password'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/paslaugu-taisykles'
    | '/privatumo-politika'
    | '/reset-password'
    | '/api/public/track'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/paslaugu-taisykles'
    | '/privatumo-politika'
    | '/reset-password'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRoute
  LoginRoute: typeof LoginRoute
  PaslauguTaisyklesRoute: typeof PaslauguTaisyklesRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paslaugu-taisykles': {
      id: '/paslaugu-taisykles'
      path: '/paslaugu-taisykles'
      fullPath: '/paslaugu-taisykles'
      preLoaderRoute: typeof PaslauguTaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRoute,
  LoginRoute: LoginRoute,
  PaslauguTaisyklesRoute: PaslauguTaisyklesRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
