/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PaslauguTaisyklesRouteImport } from './routes/paslaugu-taisykles'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as ApiPublicBookingSubmitRouteImport } from './routes/api/public/booking-submit'
import { Route as ApiPublicIcalSyncRouteImport } from './routes/api/public/ical-sync'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthenticatedAdminBookingsIndexRouteImport } from './routes/_authenticated/admin.bookings.index'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin.bookings.$id'
import { Route as AuthenticatedAdminBookingsNewRouteImport } from './routes/_authenticated/admin.bookings.new'
import { Route as AuthenticatedAdminPropertiesIndexRouteImport } from './routes/_authenticated/admin.properties.index'
import { Route as AuthenticatedAdminPropertiesNewRouteImport } from './routes/_authenticated/admin.properties.new'
import { Route as ApiPublicV1AvailabilityRouteImport } from './routes/api/public/v1/availability'
import { Route as ApiPublicV1BookingsRouteImport } from './routes/api/public/v1/bookings'
import { Route as ApiPublicV1PropertiesRouteImport } from './routes/api/public/v1/properties'
import { Route as ApiPublicV1QuoteRouteImport } from './routes/api/public/v1/quote'
import { Route as AuthenticatedAdminPropertiesIdEditRouteImport } from './routes/_authenticated/admin.properties.$id.edit'
import { Route as ApiPublicV1BookingsBookingNumberRouteImport } from './routes/api/public/v1/bookings.$bookingNumber'
import { Route as ApiPublicV1PropertiesIdRouteImport } from './routes/api/public/v1/properties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaslauguTaisyklesRoute = PaslauguTaisyklesRouteImport.update({
  id: '/paslaugu-taisykles',
  path: '/paslaugu-taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicBookingSubmitRoute = ApiPublicBookingSubmitRouteImport.update({
  id: '/api/public/booking-submit',
  path: '/api/public/booking-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIcalSyncRoute = ApiPublicIcalSyncRouteImport.update({
  id: '/api/public/ical-sync',
  path: '/api/public/ical-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBookingsIndexRoute =
  AuthenticatedAdminBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsNewRoute =
  AuthenticatedAdminBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIndexRoute =
  AuthenticatedAdminPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesNewRoute =
  AuthenticatedAdminPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1AvailabilityRoute = ApiPublicV1AvailabilityRouteImport.update({
  id: '/api/public/v1/availability',
  path: '/api/public/v1/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BookingsRoute = ApiPublicV1BookingsRouteImport.update({
  id: '/api/public/v1/bookings',
  path: '/api/public/v1/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PropertiesRoute = ApiPublicV1PropertiesRouteImport.update({
  id: '/api/public/v1/properties',
  path: '/api/public/v1/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QuoteRoute = ApiPublicV1QuoteRouteImport.update({
  id: '/api/public/v1/quote',
  path: '/api/public/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPropertiesIdEditRoute =
  AuthenticatedAdminPropertiesIdEditRouteImport.update({
    id: '/properties/$id/edit',
    path: '/properties/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1BookingsBookingNumberRoute =
  ApiPublicV1BookingsBookingNumberRouteImport.update({
    id: '/$bookingNumber',
    path: '/$bookingNumber',
    getParentRoute: () => ApiPublicV1BookingsRoute,
  } as any)
const ApiPublicV1PropertiesIdRoute = ApiPublicV1PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/paslaugu-taisykles': typeof PaslauguTaisyklesRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/public/booking-submit': typeof ApiPublicBookingSubmitRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/paslaugu-taisykles': typeof PaslauguTaisyklesRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/public/booking-submit': typeof ApiPublicBookingSubmitRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesIndexRoute
  '/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/paslaugu-taisykles': typeof PaslauguTaisyklesRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/public/booking-submit': typeof ApiPublicBookingSubmitRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/_authenticated/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/_authenticated/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/_authenticated/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/_authenticated/admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/_authenticated/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/paslaugu-taisykles'
    | '/privatumo-politika'
    | '/reset-password'
    | '/admin'
    | '/properties/$id'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/settings'
    | '/api/public/booking-submit'
    | '/api/public/ical-sync'
    | '/api/public/track'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/admin/bookings/'
    | '/admin/properties/'
    | '/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/paslaugu-taisykles'
    | '/privatumo-politika'
    | '/reset-password'
    | '/properties/$id'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/settings'
    | '/api/public/booking-submit'
    | '/api/public/ical-sync'
    | '/api/public/track'
    | '/admin'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/admin/bookings'
    | '/admin/properties'
    | '/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/paslaugu-taisykles'
    | '/privatumo-politika'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/properties/$id'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/settings'
    | '/api/public/booking-submit'
    | '/api/public/ical-sync'
    | '/api/public/track'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/bookings/$id'
    | '/_authenticated/admin/bookings/new'
    | '/_authenticated/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/_authenticated/admin/bookings/'
    | '/_authenticated/admin/properties/'
    | '/_authenticated/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OffersRoute: typeof OffersRoute
  PaslauguTaisyklesRoute: typeof PaslauguTaisyklesRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ApiPublicBookingSubmitRoute: typeof ApiPublicBookingSubmitRoute
  ApiPublicIcalSyncRoute: typeof ApiPublicIcalSyncRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicV1AvailabilityRoute: typeof ApiPublicV1AvailabilityRoute
  ApiPublicV1BookingsRoute: typeof ApiPublicV1BookingsRouteWithChildren
  ApiPublicV1PropertiesRoute: typeof ApiPublicV1PropertiesRouteWithChildren
  ApiPublicV1QuoteRoute: typeof ApiPublicV1QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paslaugu-taisykles': {
      id: '/paslaugu-taisykles'
      path: '/paslaugu-taisykles'
      fullPath: '/paslaugu-taisykles'
      preLoaderRoute: typeof PaslauguTaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/booking-submit': {
      id: '/api/public/booking-submit'
      path: '/api/public/booking-submit'
      fullPath: '/api/public/booking-submit'
      preLoaderRoute: typeof ApiPublicBookingSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ical-sync': {
      id: '/api/public/ical-sync'
      path: '/api/public/ical-sync'
      fullPath: '/api/public/ical-sync'
      preLoaderRoute: typeof ApiPublicIcalSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/bookings/': {
      id: '/_authenticated/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/new': {
      id: '/_authenticated/admin/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AuthenticatedAdminBookingsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/': {
      id: '/_authenticated/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/new': {
      id: '/_authenticated/admin/properties/new'
      path: '/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/availability': {
      id: '/api/public/v1/availability'
      path: '/api/public/v1/availability'
      fullPath: '/api/public/v1/availability'
      preLoaderRoute: typeof ApiPublicV1AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/bookings': {
      id: '/api/public/v1/bookings'
      path: '/api/public/v1/bookings'
      fullPath: '/api/public/v1/bookings'
      preLoaderRoute: typeof ApiPublicV1BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/properties': {
      id: '/api/public/v1/properties'
      path: '/api/public/v1/properties'
      fullPath: '/api/public/v1/properties'
      preLoaderRoute: typeof ApiPublicV1PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/quote': {
      id: '/api/public/v1/quote'
      path: '/api/public/v1/quote'
      fullPath: '/api/public/v1/quote'
      preLoaderRoute: typeof ApiPublicV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/properties/$id/edit': {
      id: '/_authenticated/admin/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/admin/properties/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/bookings/$bookingNumber': {
      id: '/api/public/v1/bookings/$bookingNumber'
      path: '/$bookingNumber'
      fullPath: '/api/public/v1/bookings/$bookingNumber'
      preLoaderRoute: typeof ApiPublicV1BookingsBookingNumberRouteImport
      parentRoute: typeof ApiPublicV1BookingsRoute
    }
    '/api/public/v1/properties/$id': {
      id: '/api/public/v1/properties/$id'
      path: '/$id'
      fullPath: '/api/public/v1/properties/$id'
      preLoaderRoute: typeof ApiPublicV1PropertiesIdRouteImport
      parentRoute: typeof ApiPublicV1PropertiesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
  AuthenticatedAdminBookingsNewRoute: typeof AuthenticatedAdminBookingsNewRoute
  AuthenticatedAdminPropertiesNewRoute: typeof AuthenticatedAdminPropertiesNewRoute
  AuthenticatedAdminBookingsIndexRoute: typeof AuthenticatedAdminBookingsIndexRoute
  AuthenticatedAdminPropertiesIndexRoute: typeof AuthenticatedAdminPropertiesIndexRoute
  AuthenticatedAdminPropertiesIdEditRoute: typeof AuthenticatedAdminPropertiesIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
  AuthenticatedAdminBookingsNewRoute: AuthenticatedAdminBookingsNewRoute,
  AuthenticatedAdminPropertiesNewRoute: AuthenticatedAdminPropertiesNewRoute,
  AuthenticatedAdminBookingsIndexRoute: AuthenticatedAdminBookingsIndexRoute,
  AuthenticatedAdminPropertiesIndexRoute:
    AuthenticatedAdminPropertiesIndexRoute,
  AuthenticatedAdminPropertiesIdEditRoute:
    AuthenticatedAdminPropertiesIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1BookingsRouteChildren {
  ApiPublicV1BookingsBookingNumberRoute: typeof ApiPublicV1BookingsBookingNumberRoute
}

const ApiPublicV1BookingsRouteChildren: ApiPublicV1BookingsRouteChildren = {
  ApiPublicV1BookingsBookingNumberRoute: ApiPublicV1BookingsBookingNumberRoute,
}

const ApiPublicV1BookingsRouteWithChildren =
  ApiPublicV1BookingsRoute._addFileChildren(ApiPublicV1BookingsRouteChildren)

interface ApiPublicV1PropertiesRouteChildren {
  ApiPublicV1PropertiesIdRoute: typeof ApiPublicV1PropertiesIdRoute
}

const ApiPublicV1PropertiesRouteChildren: ApiPublicV1PropertiesRouteChildren = {
  ApiPublicV1PropertiesIdRoute: ApiPublicV1PropertiesIdRoute,
}

const ApiPublicV1PropertiesRouteWithChildren =
  ApiPublicV1PropertiesRoute._addFileChildren(
    ApiPublicV1PropertiesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OffersRoute: OffersRoute,
  PaslauguTaisyklesRoute: PaslauguTaisyklesRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ApiPublicBookingSubmitRoute: ApiPublicBookingSubmitRoute,
  ApiPublicIcalSyncRoute: ApiPublicIcalSyncRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicV1AvailabilityRoute: ApiPublicV1AvailabilityRoute,
  ApiPublicV1BookingsRoute: ApiPublicV1BookingsRouteWithChildren,
  ApiPublicV1PropertiesRoute: ApiPublicV1PropertiesRouteWithChildren,
  ApiPublicV1QuoteRoute: ApiPublicV1QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
